development:
    adapter: postgresql
    encoding: utf8
    database: d57nfbpp19f7fj
    username: mkchljybibgrrh
    password: CECOxPhkk26nhQzbiFx8bmm3mA
    host: ec2-54-204-43-139.compute-1.amazonaws.com
    port: 5432

test:
    adapter: postgresql
    encoding: utf8
    database: d57nfbpp19f7fj
    username: mkchljybibgrrh
    password: CECOxPhkk26nhQzbiFx8bmm3mA
    host: ec2-54-204-43-139.compute-1.amazonaws.com
    port: 5432

production:
    adapter: postgresql
    encoding: utf8
    database: d57nfbpp19f7fj
    username: mkchljybibgrrh
    password: CECOxPhkk26nhQzbiFx8bmm3mA
    host: ec2-54-204-43-139.compute-1.amazonaws.com
    port: 5432
